# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      wget https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz
      tar -xvzf go-ipfs_v0.11.0_linux-amd64.tar.gz
      sudo bash go-ipfs/install.sh
      ipfs daemon
      curl -sL https://bacalhau.org/install.sh | bash
    command: bacalhau run echo hello
